name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: OC-D
  ACID32: 1

jobs:
  build:
    name: xcode-latest构建
    runs-on: macos-12
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: wy414012/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/ocbuild/Yaming/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: xcodebuild -jobs 1 -arch x86_64 -arch ACID32 -configuration Debug
      - run: xcodebuild -jobs 1 -arch x86_64 -arch ACID32 -configuration Release


      - name: 打包构建工件上传
        uses: actions/upload-artifact@v3
        with:
          name: Lilu-build
          path: build/*/*.zip
      - name: 上传发布版本
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true
